// +build go1.12
// +build !go1.13

package goloader

import (
	"cmd/objfile/objabi"
	"fmt"
	"strings"
)

// layout of Itab known to compilers
// allocated in non-garbage-collected memory
// Needs to be in sync with
// ../cmd/compile/internal/gc/reflect.go:/^func.dumptypestructs.
type itab struct {
	inter uintptr
	_type uintptr
	hash  uint32 // copy of _type.hash. Used for type switches.
	_     [4]byte
	fun   [1]uintptr // variable sized. fun[0]==0 means _type does not implement inter.
}

// A stackObjectRecord is generated by the compiler for each stack object in a stack frame.
// This record must match the generator code in cmd/compile/internal/gc/ssa.go:emitStackObjects.
type stackObjectRecord struct {
	// offset in frame
	// if negative, offset from varp
	// if non-negative, offset from argp
	off int
	typ *_type
}

// PCDATA and FUNCDATA table indexes.
//
// See funcdata.h and ../cmd/internal/objabi/funcdata.go.
const (
	_PCDATA_StackMapIndex       = 0
	_PCDATA_InlTreeIndex        = 1
	_PCDATA_RegMapIndex         = 2
	_FUNCDATA_ArgsPointerMaps   = 0
	_FUNCDATA_LocalsPointerMaps = 1
	_FUNCDATA_InlTree           = 2
	_FUNCDATA_RegPointerMaps    = 3
	_FUNCDATA_StackObjects      = 4
	_ArgsSizeUnknown            = -0x80000000
)

type moduledata struct {
	pclntable    []byte
	ftab         []functab
	filetab      []uint32
	findfunctab  uintptr
	minpc, maxpc uintptr

	text, etext           uintptr
	noptrdata, enoptrdata uintptr
	data, edata           uintptr
	bss, ebss             uintptr
	noptrbss, enoptrbss   uintptr
	end, gcdata, gcbss    uintptr
	types, etypes         uintptr

	textsectmap []textsect
	typelinks   []int32 // offsets from types
	itablinks   []*itab

	ptab []ptabEntry

	pluginpath string
	pkghashes  []modulehash

	modulename   string
	modulehashes []modulehash

	hasmain uint8 // 1 if module contains the main function, 0 otherwise

	gcdatamask, gcbssmask bitvector

	typemap map[typeOff]uintptr // offset to *_rtype in previous module

	bad bool // module failed to load and should be ignored

	next *moduledata
}

// A funcID identifies particular functions that need to be treated
// specially by the runtime.
// Note that in some situations involving plugins, there may be multiple
// copies of a particular special runtime function.
// Note: this list must match the list in cmd/internal/objabi/funcid.go.
type funcID uint8

type _func struct {
	entry   uintptr // start pc
	nameoff int32   // function name

	args int32 // in/out args size
	_    int32 // previously legacy frame size; kept for layout compatibility

	pcsp      int32
	pcfile    int32
	pcln      int32
	npcdata   int32
	funcID    funcID  // set for certain special runtime functions
	_         [2]int8 // unused
	nfuncdata uint8
}

func readFuncData(module *Module, curSymFile symFile,
	allSyms map[string]symFile, gcObjs map[string]uintptr,
	fileTabOffsetMap map[string]int, curSymOffset, curCodeLen int) {

	fs := readAtSeeker{ReadSeeker: curSymFile.file}
	curSym := curSymFile.sym

	{
		x := curCodeLen
		b := x / pcbucketsize
		i := x % pcbucketsize / (pcbucketsize / nsub)
		for lb := b - len(module.pcfunc); lb >= 0; lb-- {
			module.pcfunc = append(module.pcfunc, findfuncbucket{
				idx: uint32(256 * len(module.pcfunc))})
		}
		bucket := &module.pcfunc[b]
		bucket.subbuckets[i] = byte(len(module.ftab) - int(bucket.idx))
	}

	var fileTabOffset = len(module.filetab)
	var fileOffsets []uint32
	var fullFile string
	for _, fileName := range curSym.Func.File {
		fileOffsets = append(fileOffsets, uint32(len(fullFile)+len(module.pclntable)))
		fileName = strings.TrimLeft(curSym.Func.File[0], "gofile..")
		fullFile += fileName + "\x00"
	}
	if tabOffset, ok := fileTabOffsetMap[fullFile]; !ok {
		module.pclntable = append(module.pclntable, []byte(fullFile)...)
		fileTabOffsetMap[fullFile] = fileTabOffset
		module.filetab = append(module.filetab, fileOffsets...)
	} else {
		fileTabOffset = tabOffset
	}
	var pcFileHead [2]byte
	if fileTabOffset > 128 {
		fmt.Println("filetab overflow!")
	}
	pcFileHead[0] = byte(fileTabOffset << 1)

	nameOff := len(module.pclntable)
	nameByte := make([]byte, len(curSym.Name)+1)
	copy(nameByte, []byte(curSym.Name))
	module.pclntable = append(module.pclntable, nameByte...)

	spOff := len(module.pclntable)
	var fb = make([]byte, curSym.Func.PCSP.Size)
	fs.ReadAt(fb, curSym.Func.PCSP.Offset)
	// fmt.Println("sp val:", fb)
	module.pclntable = append(module.pclntable, fb...)

	pcfileOff := len(module.pclntable)
	fb = make([]byte, curSym.Func.PCFile.Size)
	fs.ReadAt(fb, curSym.Func.PCFile.Offset)
	// dumpPCData(fb, "pcfile")
	module.pclntable = append(module.pclntable, pcFileHead[:]...)
	module.pclntable = append(module.pclntable, fb...)

	pclnOff := len(module.pclntable)
	fb = make([]byte, curSym.Func.PCLine.Size)
	fs.ReadAt(fb, curSym.Func.PCLine.Offset)
	module.pclntable = append(module.pclntable, fb...)

	var file string
	if curSym.Func != nil && len(curSym.Func.File) > 0 {
		file = strings.TrimLeft(curSym.Func.File[0], "gofile..")
	}
	fdata := _func{
		entry:     uintptr(curSymOffset),
		nameoff:   int32(nameOff),
		args:      int32(curSym.Func.Args),
		pcsp:      int32(spOff),
		pcfile:    int32(pcfileOff),
		pcln:      int32(pclnOff),
		npcdata:   int32(len(curSym.Func.PCData)),
		funcID:    funcID(objabi.GetFuncID(curSym.Name, file)),
		nfuncdata: uint8(len(curSym.Func.FuncData)),
	}
	var fInfo funcInfoData
	fInfo._func = fdata
	for _, data := range curSym.Func.PCData {
		fInfo.pcdata = append(fInfo.pcdata, uint32(len(module.pclntable)))

		var b = make([]byte, data.Size)
		fs.ReadAt(b, data.Offset)
		// dumpPCData(b)
		module.pclntable = append(module.pclntable, b...)
	}
	for _, data := range curSym.Func.FuncData {
		var offset uintptr
		if off, ok := gcObjs[data.Sym.Name]; !ok {
			if gcobj, ok := allSyms[data.Sym.Name]; ok {
				var b = make([]byte, gcobj.sym.Data.Size)
				cfs := readAtSeeker{ReadSeeker: gcobj.file}
				cfs.ReadAt(b, gcobj.sym.Data.Offset)
				offset = uintptr(len(module.stkmaps))
				module.stkmaps = append(module.stkmaps, b)
				gcObjs[data.Sym.Name] = offset
			} else if len(data.Sym.Name) == 0 {
				offset = 0
			} else {
				fmt.Println("unknown gcobj:", data.Sym.Name)
			}
		} else {
			offset = off
		}

		fInfo.funcdata = append(fInfo.funcdata, offset)
	}
	fInfo.Var = curSym.Func.Var

	module.ftab = append(module.ftab, functab{
		entry: uintptr(curSymOffset),
	})

	module.funcinfo = append(module.funcinfo, fInfo)
}
