name: goloader Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: auto
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x, 1.20.x]
        os:  [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: macos-latest
            go-version: 1.8.x
          - os: macos-latest
            go-version: 1.9.x
          - os: macos-latest
            go-version: 1.10.x
        include:
          - os: macos-11
            go-version: 1.8.x
          - os: macos-11
            go-version: 1.9.x
          - os: macos-11
            go-version: 1.10.x
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Rename cmd/internal
      shell: sh
      run:         
        cp -r `go env GOROOT`/src/cmd/internal `go env GOROOT`/src/cmd/objfile
        
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      
    - name: Build
      run:
        go build github.com/pkujhd/goloader/examples/loader
        
    - name: Compile const.go
      shell: sh
      run: |
        if [ `echo ${{ matrix.go-version }} | cut -d'.' -f2` -ge 20 ]; then
          go list -export -f '{{if .Export}}packagefile {{.ImportPath}}={{.Export}}{{end}}' std `go list -f {{.Imports}} $GOPATH/src/github.com/pkujhd/goloader/examples/const/const.go | awk '{sub(/^\[/, ""); print }' | awk '{sub(/\]$/, ""); print }'` > importcfg
          go tool compile -importcfg importcfg $GOPATH/src/github.com/pkujhd/goloader/examples/const/const.go
        else
          go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/const/const.go
        fi
        
    - name: Compile base.go
      shell: sh
      run: |
        if [ `echo ${{ matrix.go-version }} | cut -d'.' -f2` -ge 20 ]; then
          go list -export -f '{{if .Export}}packagefile {{.ImportPath}}={{.Export}}{{end}}' std `go list -f {{.Imports}} $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go | awk '{sub(/^\[/, ""); print }' | awk '{sub(/\]$/, ""); print }'` > importcfg
          go tool compile -importcfg importcfg $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go
        else
          go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go
        fi
        
    - name: Test base.o
      run: 
        ./loader -o base.o -run main.main
        
    - name: Test const.o
      run:
        ./loader -o const.o -run main.main
